name: Sync GitHub to Gitee

on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sync to Gitee
      env:
        GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
        GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
        GITEE_REPO: ${{ secrets.GITEE_REPO }}
      run: |
        git config --global user.name "${{ secrets.GITEE_USERNAME }}"
        git config --global user.email "${{ secrets.GITEE_EMAIL }}"
        git remote add gitee https://gitee.com/${{ secrets.GITEE_USERNAME }}/${{ secrets.GITEE_REPO }}.git
        git push gitee main --force
